/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElProgress: typeof import('element-plus/es')['ElProgress']
  }
}
